'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Bell, Check, ChevronDown, ChevronRight, CircleHelp, Coffee, Home, Leaf, MoreHorizontal, PackageOpen, Plus, ReceiptText, ScanLine, Settings2, ShoppingBag, Sparkles, Trash2, Upload, X } from 'lucide-react';

type Item = { name: string; emoji: string; amount: string; remaining: string; due: string; confidence: number; cadence: string; status: 'Soon' | 'This week' | 'Later'; selected: boolean };
const starterItems: Item[] = [
  { name: 'Whole milk', emoji: '🥛', amount: '1 carton', remaining: 'About 1/4 left', due: 'Tuesday', confidence: 96, cadence: 'Usually every 6 days', status: 'Soon', selected: true },
  { name: 'Eggs', emoji: '🥚', amount: '6 pack', remaining: 'About 4 left', due: 'Thursday', confidence: 91, cadence: 'Usually every 9 days', status: 'This week', selected: true },
  { name: 'Sourdough', emoji: '🍞', amount: '1 loaf', remaining: 'About 1/3 left', due: 'Wednesday', confidence: 89, cadence: 'Usually every 5 days', status: 'Soon', selected: true },
  { name: 'Coffee beans', emoji: '☕', amount: '340 g bag', remaining: 'About 1/3 left', due: 'Jul 24', confidence: 82, cadence: 'Usually every 18 days', status: 'Later', selected: true },
  { name: 'Olive oil', emoji: '🫒', amount: '500 ml', remaining: 'About half left', due: 'Jul 30', confidence: 64, cadence: 'Still learning your rhythm', status: 'Later', selected: false },
];

export default function HomePage() {
  const [items, setItems] = useState(starterItems);
  const [tab, setTab] = useState<'home' | 'inventory' | 'history' | 'household'>('home');
  const [uploadOpen, setUploadOpen] = useState(false);
  const [uploaded, setUploaded] = useState(false);
  const [detail, setDetail] = useState<Item | null>(null);
  const [toast, setToast] = useState('');
  const [household, setHousehold] = useState({ adults: '2', children: '0', pets: '1', cadence: 'Weekly', day: 'Friday', cooking: 'Most nights', preferences: 'Vegetarian-friendly' });
  const selected = useMemo(() => items.filter(i => i.selected), [items]);
  const toggle = (name: string) => setItems(previous => previous.map(i => i.name === name ? { ...i, selected: !i.selected } : i));
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  const nav = (target: 'home' | 'inventory' | 'history' | 'household') => setTab(target);

  return <main className="min-h-screen bg-[#f7f8f4] text-[#17261f]">
    <header className="sticky top-0 z-20 border-b border-[#e5e9df] bg-[#f7f8f4]/90 backdrop-blur">
      <div className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-5">
        <button onClick={() => nav('home')} className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#1d5b45] text-lg text-white">m</span><span className="text-lg font-semibold tracking-tight">milo</span></button>
        <div className="flex items-center gap-3"><button className="relative rounded-full p-2 hover:bg-white"><Bell size={19}/><span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-[#e7794b]"/></button><button className="flex items-center gap-2 rounded-full border border-[#dce3d8] bg-white py-1.5 pl-2 pr-3 text-sm font-medium"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dceedd] text-xs">MU</span>Melissa<ChevronDown size={15}/></button></div>
      </div>
    </header>

    <div className="mx-auto grid max-w-6xl grid-cols-1 gap-8 px-5 py-7 md:grid-cols-[176px_1fr]">
      <aside className="hidden md:block"><nav className="space-y-1 text-sm font-medium text-[#617067]">
        <NavButton icon={<Home size={18}/>} label="Home" active={tab === 'home'} onClick={() => nav('home')}/>
        <NavButton icon={<PackageOpen size={18}/>} label="My pantry" active={tab === 'inventory'} onClick={() => nav('inventory')}/>
        <NavButton icon={<ReceiptText size={18}/>} label="Shopping history" active={tab === 'history'} onClick={() => nav('history')}/>
        <NavButton icon={<Settings2 size={18}/>} label="Household" active={tab === 'household'} onClick={() => nav('household')}/>
      </nav><div className="mt-10 rounded-2xl bg-[#e7f2e7] p-4"><Sparkles size={18} className="text-[#317051]"/><p className="mt-2 text-sm font-semibold">Milo is learning</p><p className="mt-1 text-xs leading-5 text-[#5c7162]">You&apos;ve helped improve 14 predictions this month.</p></div></aside>

      <section className="min-w-0 pb-20">
        {tab === 'home' && <HomeView selected={selected} items={items} onToggle={toggle} onDetail={setDetail} onUpload={() => setUploadOpen(true)} onList={() => notify(`${selected.length} items are ready for your shopping list.`)} />}
        {tab === 'inventory' && <InventoryView items={items} onDetail={setDetail} onUpload={() => setUploadOpen(true)} />}
        {tab === 'history' && <HistoryView onUpload={() => setUploadOpen(true)} />}
        {tab === 'household' && <HouseholdView household={household} onChange={(field, value) => setHousehold(current => ({ ...current, [field]: value }))} onSave={() => notify('Household settings saved. Milo will use these for future predictions.')} />}
      </section>
    </div>

    <nav className="fixed bottom-0 left-0 right-0 z-20 flex justify-around border-t border-[#e5e9df] bg-white px-5 py-2 md:hidden"><MobileNav icon={<Home size={19}/>} label="Home" active={tab === 'home'} onClick={() => nav('home')}/><MobileNav icon={<PackageOpen size={19}/>} label="Pantry" active={tab === 'inventory'} onClick={() => nav('inventory')}/><button onClick={() => setUploadOpen(true)} className="-mt-6 grid h-13 w-13 place-items-center rounded-full bg-[#1d5b45] text-white shadow-lg"><Plus size={23}/></button><MobileNav icon={<ReceiptText size={19}/>} label="History" active={tab === 'history'} onClick={() => nav('history')}/><MobileNav icon={<Settings2 size={19}/>} label="Profile" active={tab === 'household'} onClick={() => nav('household')}/></nav>
    {uploadOpen && <UploadModal uploaded={uploaded} onClose={() => setUploadOpen(false)} onUpload={() => { setUploaded(true); window.setTimeout(() => { setUploadOpen(false); notify('7 items added to your household intelligence.'); }, 850); }} />}
    {detail && <DetailModal item={detail} onClose={() => setDetail(null)} onRemove={() => { toggle(detail.name); setDetail(null); notify(`Milo will learn from removing ${detail.name}.`); }} />}
    {toast && <div className="fixed bottom-24 left-1/2 z-40 -translate-x-1/2 rounded-full bg-[#17261f] px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}
  </main>;
}

function HomeView({ selected, items, onToggle, onDetail, onUpload, onList }: { selected: Item[]; items: Item[]; onToggle: (n:string)=>void; onDetail:(i:Item)=>void; onUpload:()=>void; onList:()=>void }) { return <>
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-[#5e7166]">Thursday, July 16</p><h1 className="mt-1 text-3xl font-semibold tracking-tight md:text-[34px]">Good morning, Melissa.</h1></div><button onClick={onUpload} className="inline-flex items-center gap-2 rounded-full border border-[#d5e1d5] bg-white px-4 py-2.5 text-sm font-semibold shadow-sm hover:bg-[#f2f7f0]"><Upload size={16}/>Add a receipt</button></div>
  <div className="mt-7 overflow-hidden rounded-3xl bg-[#1d5b45] p-6 text-white shadow-sm md:p-8"><div className="flex items-start justify-between"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-white/12 px-3 py-1 text-xs font-medium text-[#d4ead7]"><Sparkles size={13}/>Your next shop</span><h2 className="mt-4 max-w-xl text-2xl font-medium leading-tight md:text-3xl">You&apos;ll likely do groceries tomorrow.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#d7e8dc]">Based on your recent rhythm, a Friday shop is 86% likely. I&apos;ve prepared what will keep your household covered for the week ahead.</p></div><span className="hidden text-5xl md:block">🛍️</span></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={onList} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-[#19523f]">View shopping list <ArrowRight size={16}/></button><button onClick={onUpload} className="rounded-full border border-white/25 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/10">Update what I bought</button></div></div>
  <div className="mt-8 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#6c7d72]">Recommended for tomorrow</p><h2 className="mt-1 text-xl font-semibold">A little less to remember</h2></div><button onClick={() => onList()} className="hidden text-sm font-semibold text-[#2b6b50] sm:block">{selected.length} items selected</button></div>
  <div className="mt-4 space-y-3">{items.map(item => <Recommendation key={item.name} item={item} onToggle={onToggle} onDetail={onDetail}/>)}</div>
  <div className="mt-7 rounded-2xl border border-[#e2e7de] bg-white p-5"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#eef5eb] text-[#2c714e]"><CircleHelp size={18}/></div><div><h3 className="font-semibold">Why these recommendations?</h3><p className="mt-1 text-sm leading-6 text-[#67786e]">Milo combines your past purchases, estimated remaining supply, and your usual 7-day shopping rhythm. Tap any item to see the reasoning—and tell us when we&apos;re wrong.</p></div></div></div>
</> }

function Recommendation({ item, onToggle, onDetail }: { item:Item; onToggle:(n:string)=>void; onDetail:(i:Item)=>void }) { const color = item.confidence > 85 ? 'bg-[#e5f2e6] text-[#28704c]' : item.confidence > 70 ? 'bg-[#fff1dc] text-[#9a6419]' : 'bg-[#f0f1ee] text-[#6c736d]'; return <article className="group flex items-center gap-3 rounded-2xl border border-[#e2e7de] bg-white p-4 transition hover:border-[#bdceb9]"><button aria-label={`Toggle ${item.name}`} onClick={() => onToggle(item.name)} className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border ${item.selected ? 'border-[#28704c] bg-[#28704c] text-white' : 'border-[#bdc8be] text-transparent'}`}><Check size={15}/></button><button onClick={() => onDetail(item)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#f3f5f0] text-xl">{item.emoji}</span><span className="min-w-0"><span className="block font-semibold">{item.name}</span><span className="mt-0.5 block truncate text-sm text-[#728077]">{item.remaining} · likely out {item.due}</span></span></button><div className="hidden text-right sm:block"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${color}`}>{item.confidence}% sure</span><span className="mt-1.5 block text-xs text-[#78857d]">{item.cadence}</span></div><ChevronRight size={19} className="text-[#9aaba0]"/></article> }

function InventoryView({items,onDetail,onUpload}:{items:Item[];onDetail:(i:Item)=>void;onUpload:()=>void}) { return <><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-[#5e7166]">Your living inventory</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">My pantry</h1><p className="mt-2 text-sm text-[#708076]">A practical picture—not a perfect count.</p></div><button onClick={onUpload} className="rounded-full bg-[#1d5b45] p-3 text-white"><Plus size={18}/></button></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{items.map(i => <button key={i.name} onClick={() => onDetail(i)} className="rounded-2xl border border-[#e2e7de] bg-white p-5 text-left hover:border-[#bdceb9]"><div className="flex items-start justify-between"><span className="text-3xl">{i.emoji}</span><span className="rounded-full bg-[#f2f4f0] px-2.5 py-1 text-xs font-medium text-[#637168]">{i.amount}</span></div><p className="mt-5 font-semibold">{i.name}</p><p className="mt-1 text-sm text-[#718076]">{i.remaining}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#edf0eb]"><div className="h-full rounded-full bg-[#6ca976]" style={{width: `${Math.max(18, 100 - i.confidence)}%`}}/></div></button>)}</div></> }

function HouseholdView({ household, onChange, onSave }: { household: { adults: string; children: string; pets: string; cadence: string; day: string; cooking: string; preferences: string }; onChange: (field: keyof { adults: string; children: string; pets: string; cadence: string; day: string; cooking: string; preferences: string }, value: string) => void; onSave: () => void }) { return <><div><p className="text-sm font-medium text-[#5e7166]">The context behind your predictions</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Your household</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#708076]">Milo uses these details to make a stronger starting estimate, then learns from what you actually buy.</p></div><div className="mt-7 space-y-5"><section className="rounded-2xl border border-[#e2e7de] bg-white p-5"><h2 className="font-semibold">Who&apos;s at home?</h2><div className="mt-4 grid grid-cols-3 gap-3"><SettingField label="Adults" value={household.adults} onChange={v => onChange('adults', v)} /><SettingField label="Children" value={household.children} onChange={v => onChange('children', v)} /><SettingField label="Pets" value={household.pets} onChange={v => onChange('pets', v)} /></div></section><section className="rounded-2xl border border-[#e2e7de] bg-white p-5"><h2 className="font-semibold">Shopping rhythm</h2><p className="mt-1 text-sm text-[#718077]">This helps Milo get started. Your actual behavior will take over.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><SelectField label="Usual frequency" value={household.cadence} options={['Weekly', 'Every 10 days', 'Every two weeks', 'It varies']} onChange={v => onChange('cadence', v)} /><SelectField label="Usual shopping day" value={household.day} options={['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'No usual day']} onChange={v => onChange('day', v)} /></div></section><section className="rounded-2xl border border-[#e2e7de] bg-white p-5"><h2 className="font-semibold">Everyday habits</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><SelectField label="Cooking at home" value={household.cooking} options={['Most nights', 'A few nights a week', 'Rarely']} onChange={v => onChange('cooking', v)} /><SelectField label="Food preferences" value={household.preferences} options={['Vegetarian-friendly', 'No preferences', 'Vegan', 'Gluten-free', 'Family-friendly']} onChange={v => onChange('preferences', v)} /></div></section></div><button onClick={onSave} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#1d5b45] px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#174a38]"><Check size={16}/>Save household settings</button></> }

function SettingField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-[#596b60]">{label}<input aria-label={label} inputMode="numeric" value={value} onChange={event => onChange(event.target.value.replace(/[^0-9]/g, ''))} className="mt-2 w-full rounded-xl border border-[#dce5da] bg-[#fbfdf9] px-3 py-2.5 text-base font-semibold text-[#17261f] outline-none focus:border-[#4b8460]" /></label> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-[#596b60]">{label}<select aria-label={label} value={value} onChange={event => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-[#dce5da] bg-[#fbfdf9] px-3 py-2.5 text-sm font-medium text-[#17261f] outline-none focus:border-[#4b8460]">{options.map(option => <option key={option}>{option}</option>)}</select></label> }

function HistoryView({onUpload}:{onUpload:()=>void}) { const purchases = [['Jul 11','REWE','18 items','€64.20'],['Jul 4','REWE','14 items','€52.80'],['Jun 27','EDEKA','21 items','€71.45']]; return <><p className="text-sm font-medium text-[#5e7166]">What Milo has learned from</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Shopping history</h1><div className="mt-7 overflow-hidden rounded-2xl border border-[#e2e7de] bg-white">{purchases.map((p,i) => <div key={p[0]} className="flex items-center gap-4 border-b border-[#edf0eb] p-5 last:border-0"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef5eb] text-[#28704c]"><ShoppingBag size={18}/></span><div className="flex-1"><p className="font-semibold">{p[1]}</p><p className="text-sm text-[#738077]">{p[0]} · {p[2]}</p></div><span className="text-sm font-medium">{p[3]}</span><ChevronRight size={18} className="text-[#9aa79f]"/></div>)}</div><button onClick={onUpload} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-[#b9cbb9] bg-[#fbfdf9] p-7 text-sm font-semibold text-[#347054]"><ScanLine size={19}/>Scan another receipt</button></> }

function UploadModal({uploaded,onClose,onUpload}:{uploaded:boolean;onClose:()=>void;onUpload:()=>void}) { return <div className="fixed inset-0 z-40 grid place-items-end bg-[#10231a]/35 p-0 sm:place-items-center sm:p-5"><div className="w-full max-w-md rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#6c7e72]">Teach Milo</p><h2 className="mt-1 text-xl font-semibold">Add what you bought</h2></div><button onClick={onClose} className="rounded-full p-2 hover:bg-[#f4f6f2]"><X size={19}/></button></div>{uploaded ? <div className="py-12 text-center"><span className="text-5xl">✨</span><h3 className="mt-4 text-lg font-semibold">Receipt understood</h3><p className="mt-2 text-sm text-[#6c7a72]">I found 7 products and updated your predictions.</p></div> : <><button onClick={onUpload} className="mt-6 grid w-full place-items-center rounded-2xl border-2 border-dashed border-[#bcd0bd] bg-[#f7fbf5] p-9 text-center hover:bg-[#f1f8ee]"><span className="grid h-12 w-12 place-items-center rounded-full bg-white text-[#2f6e4d] shadow-sm"><ReceiptText size={22}/></span><span className="mt-3 font-semibold">Upload a receipt or bag photo</span><span className="mt-1 text-sm text-[#718077]">Milo will identify products and quantities</span></button><div className="my-5 flex items-center gap-3 text-xs text-[#a0aaa2]"><span className="h-px flex-1 bg-[#e7ebe5]"/>OR<span className="h-px flex-1 bg-[#e7ebe5]"/></div><button onClick={() => alert('Manual addition is ready for the next demo step.')} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#dce5da] py-3 text-sm font-semibold"><Plus size={16}/>Add products manually</button></>}</div></div> }

function DetailModal({item,onClose,onRemove}:{item:Item;onClose:()=>void;onRemove:()=>void}) { return <div className="fixed inset-0 z-40 grid place-items-end bg-[#10231a]/35 sm:place-items-center"><div className="w-full max-w-md rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex justify-between"><span className="text-4xl">{item.emoji}</span><button onClick={onClose} className="rounded-full p-2 hover:bg-[#f4f6f2]"><X size={19}/></button></div><h2 className="mt-4 text-2xl font-semibold">{item.name}</h2><p className="mt-1 text-sm text-[#718077]">Milo is {item.confidence}% confident in this prediction.</p><div className="mt-6 rounded-2xl bg-[#eff6ec] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#28704c]"><Sparkles size={16}/>Why this is on your list</div><p className="mt-2 text-sm leading-6 text-[#52705c]">Your household typically uses {item.name.toLowerCase()} {item.cadence.replace('Usually ', '').toLowerCase()}. You last bought it 4 days ago and have {item.remaining.toLowerCase()}. At your next likely shop tomorrow, you&apos;ll be close to running out by {item.due}.</p></div><button onClick={onRemove} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold text-[#9d4a3d] hover:bg-[#fdf1ef]"><Trash2 size={16}/>I don&apos;t need this</button></div></div> }

function NavButton({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}) { return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${active ? 'bg-[#e7f1e5] text-[#1d5b45]' : 'hover:bg-white hover:text-[#2c4034]'}`}>{icon}{label}</button> }
function MobileNav({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}) { return <button onClick={onClick} className={`grid justify-items-center gap-0.5 text-[10px] ${active ? 'text-[#1d5b45]' : 'text-[#819087]'}`}>{icon}{label}</button> }
